apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::710019170268:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LXHW9PCZSTIQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-27T18:27:29Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-01-27T18:27:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1598"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d78f4d7e-e22c-4de9-9094-baa6bc94c53d
